# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Stephanie Montoya
title: Metro Technology Center Student 
email: stephanie.montoya@st.metrotech.edu
website: 

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username:
github_username:  MetroSteph
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 
linkedin_username: 
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username:
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: 
  icon:
  url: 
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Stephanie and I'm a student at Metro Technology Center, I am currently enrolled in Cybersecurity Network Specialist. I am driven and passionate about learning cybersecurity basics like threat detection, network security and data protection. I'm diving into online courses like Python, Kali Linux and Git to be able to build a strong foundation, and I'm excited to continue learning more about this career. 

  I am most skilled in: <mark>Video gaming</mark> and <mark>Being a nerd</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Oklahoma Heart Hospital
        link: 
        # link_text: Project Website
        sub_title: Security Officer II
        caption: January 2017 - Present
        additional_links:
          - title:  
            icon: 
            url: 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         
        description: | # this will include new lines to allow paragraphs
         Experienced armed security officer trained to handle emerygency situations, conducting regular patrols, and repsonding to alarms and incidents.
   
   
    - title: Qualifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SOR Traning Center
        link: https://www.sortrainingcenter.com/
         sub_title: Phase 1 & 2
        caption: 
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Security Officer traning to equip officers with essential skills. Teaches basic skills,patrol methods, and how to respond to emergencies, also focuses on more advanced skills, such as handling crises, writing reports, and using defensive tactics.       
   
          - title: Qualifications  # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SOR Traning Center
        link: https://www.sortrainingcenter.com/
        caption: 
        sub_title: Phase 4
        quote: >
         
        description: | # this will include new lines to allow paragraphs
           Firearm training teaches officers how to safely use and handle firearms. It covers gun safety, shooting skills, legal rules, and when to use force, preparing officers for high-risk situations.

- title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in security and Cybersecurity some of my other interests and hobbies are:
      - Watching Youtube 
      - Gaming
      - Reading about new technology
  

      
  

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
